services:
  privaxnet_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - privaxnet_api_network

networks:
  privaxnet_api_network:
    driver: bridge
      